my_project:
  mainapp:
    - __init__.py
    - models.py
    - views.py
    - templates:
        - mainapp:
            - base.html
            - index.html
  authapp:
    - __init__.py
    - models.py
    - views.py  
    - templates:
        - mainapp:
            - base.html
            - index.html